# === Basic Config ===
alg_name: sft
layers: [14]
use_cache: false

# === Dataset Config ===
exclude_bos: true
max_concepts: 1
max_num_of_examples: null
preference_pairs: ["orig_add", "orig_sub"] # use_cmd_to_define
output_length: 512

# === Training Config ===
batch_size: 1 # the actual batch size also needs to multiply with |preference_pairs|
dropout: 0.1
gradient_accumulation_steps: 1
lr: 0.08
n_epochs: 1
weight_decay: 0.00      

sft_preference_type: "winning_only"
loss_output_dir: null
inference: true

# === Intervention Config ===
intervention_positions: "all"
intervention_positions_dropout: 0.0
intervention_type: "addition" # clamping
low_rank_dimension: 1
intervention_method: "vector"

# === Steering Config ===
steering_factors: [1.0] # use_cmd_to_define
steering_prompt_type: "blend_in"
substraction_type: "normal" # normal or null_it_out