name: "🐛 Bug Report"
description: Submit a bug report to help us improve EasyEdit
labels: [ "bug" ]
body:
  - type: textarea
    id: describe-bug
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and concise description of the bug you encountered.
      placeholder: |
        e.g., When editing a sentence using MEND, the output is unexpectedly unchanged.

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: To Reproduce
      description: |
        Before reporting a bug, please ensure you have thoroughly reviewed the following:

        - [README.md (EasyEdit1)](https://github.com/zjunlp/EasyEdit/blob/main/README.md)
        - [README_2.md (EasyEdit2)](https://github.com/zjunlp/EasyEdit/blob/main/README_2.md)

        Then, provide **clear reproduction steps**, including:
        - Your environment (Python version, OS, dependency versions, etc.)
        - The full script or commands used to reproduce the issue

        ✅ Please submit code using correctly formatted [code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting)  
        📷 Long error messages can be provided as screenshots if needed.

        These help developers reproduce and resolve your issue more efficiently.
      placeholder: |
        Steps to reproduce the behavior:
        
          1. Code and Environment 
          2. Run:
             ```bash
             ```
          3. Observe error:
             ```text
             Traceback (most recent call last):
               ...
             ```
        
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen instead?