name: "✨ Feature Request"
description: Suggest a new feature or improvement for EasyEdit
labels: [ "enhancement" ]
body:
  - type: checkboxes
    id: context
    attributes:
      label: Use context
      description: "This feature relates to:"
      options:
        - label: "A specific editing method (e.g., MEND, SERAC, ROME)"
        - label: "Support for a new model or architecture"
        - label: "Improved APIs or usability"
        - label: "Evaluation metrics or logging"
        - label: "Other (please describe below)"

  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: What problem are you facing?
      description: |
        Describe the limitation, missing capability, or difficulty you encountered while using EasyEdit.
        Try to include relevant context or examples that motivated your request.
      placeholder: |
        e.g., It's hard to apply MEND to LLaMA-style models due to the current implementation relying on HuggingFace-compatible architectures.

  - type: textarea
    id: proposal
    validations:
      required: true
    attributes:
      label: Describe the feature you'd like to see
      description: |
        Describe your proposed feature or enhancement clearly. Focus on what you'd like to achieve.
        If applicable, suggest interface designs or example usage.
      placeholder: |
        e.g., Add support for LLaMA through a wrapper module so that MEND can be applied without changing core code.

  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternatives?
      description: |
        Describe any workarounds or alternative solutions you've considered, and why they may not be ideal.
      placeholder: |
        e.g., I tried manually converting model weights, but it's error-prone and incompatible with downstream evaluation scripts.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other information, references, or related issues/PRs that might help us evaluate your request.
      placeholder: |
        e.g., This feature would enable applying model editing to non-HF models like Baichuan, InternLM, etc., which are increasingly popular in the community.

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true