# Model
model_name: /mnt/xzk/Baichuan-7B
model_class: LlamaForCausalLM
small_name: /mnt/peng/EasyEdit/hugging_cache/llama-160m
tokenizer_class: LlamaTokenizer
tokenizer_name: /mnt/xzk/Baichuan-7B
cls_name: /mnt/peng/EasyEdit/hugging_cache/distilbert-base-cased
cls_class: AutoModel
inner_params: []

archive: null

# Method
alg: SERAC
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null

device: cuda:0
batch_size: 10
model_save_pt: 1000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 100000
log_interval: 1000
val_interval: 1000
early_stop_patience: 30000
early_stop_key: "edit/acc_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 10
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results
