alg_name: reps
layers: [20]
multiple_choice: false

batch_size: 6 # the actual batch size also needs to multiply with |preference_pairs|
gradient_accumulation_steps: 1
n_epochs: 18
lr: 0.08
weight_decay: 0.00
low_rank_dimension: 1
intervention_positions: "all"
intervention_type: "addition" # clamping
# binarize_dataset: false
train_on_negative: true
exclude_bos: true
loss_type: "scaled_simpo"
beta: 1.0
gemma: 0.0
simpo_scaler: 1.0
label_smoothing: 0.0
dropout: 0.1
intervention_positions_dropout: 0.0
steering_factors: [2.0] # use_cmd_to_define
preference_pairs: ["orig_add", "orig_sub"] # use_cmd_to_define
steering_prompt_type: "blend_in"
substraction_type: "null_it_out" # normal or null_it_ou




