# Model specific
alg_name: lm_steer
adaptor_class: "multiply"
adapted_component: "final_layer"
epsilon: 0.001
init_var: 0.01
rank: 4000
num_steers: 2

# Training specific
regularization: 0
optimizer: "Adam"
lr: 0.01
gamma_mean: 0.99
n_steps: 300
max_length: 256
batch_size: 8
log_step: 100
subset: null
dummy_steer: 1
training_steer: 0
low_resource_mode: null



