alg_name: "LoRA"
model_name: "openai-community/gpt2-xl"
device: 0

lora_type: "adalora"
layers: []
num_steps: 30
batch_size: 1
max_length: 30
lr: 5e-3
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["c_attn"] 
model_parallel: true