# === Basic Config ===
alg_name: sft
layers: [20]
use_cache: false

# === Dataset Config ===
exclude_bos: true
max_concepts: 1
max_num_of_examples: null
preference_pairs: ["orig_add"] # use_cmd_to_define
output_length: 512

# === Training Config ===
batch_size: 4 # the actual batch size also needs to multiply with |preference_pairs|
dropout: 0.1
gradient_accumulation_steps: 1
lr: 0.08
n_epochs: 2
weight_decay: 0.00
pos_loss_weight: 1.0  
neg_loss_weight: 0.5  
margin_penalty_weight: 5  
ref_loss_weight: 0.0       
margin_threshold: 0.5      

loss_output_dir: null
inference: false

# === Intervention Config ===
intervention_positions: "all"
intervention_positions_dropout: 0.0
intervention_type: "addition" # clamping
low_rank_dimension: 1
intervention_method: "vector"

# === Steering Config ===
steering_factors: [2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0] # use_cmd_to_define
steering_prompt_type: "blend_in"
substraction_type: "normal" # normal or null_it_out





