# === Basic Config ===
alg_name: reps
layers: [14]
use_cache: false

# === Dataset Config ===
exclude_bos: true
max_concepts: 1
max_num_of_examples: null
preference_pairs: ["orig_add", "orig_sub"] # use_cmd_to_define
output_length: 512

# === Training Config ===
batch_size: 4 # the actual batch size also needs to multiply with |preference_pairs|
beta: 1.0
dropout: 0.1
gemma: 0.0
gradient_accumulation_steps: 1
label_smoothing: 0.0
loss_type: "scaled_simpo"
lr: 0.08
n_epochs: 2
reference_free: false
simpo_scaler: 1.0
train_on_negative: true
weight_decay: 0.00

# === Intervention Config ===
intervention_positions: "all"
intervention_positions_dropout: 0.0
intervention_type: "addition" # clamping
low_rank_dimension: 1
intervention_method: "vector"

# === Steering Config ===
steering_factors: [2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0] # use_cmd_to_define
# steering_factors: [1.0] # use_cmd_to_define
steering_prompt_type: "blend_in"
substraction_type: "null_it_out" # normal or null_it_out
# substraction_type: "normal" # normal or null_it_out





