# === Basic Config ===
alg_name: reps_vector
layers: [20]
save_vectors: true
steer_vector_output_dir: "../"
use_cache: false

# === Dataset Config ===
exclude_bos: true
max_concepts: 1
max_num_of_examples: 10000
steer_train_dataset: "safeedit"
preference_pairs: ["orig_add", "orig_sub"] # use_cmd_to_define

# === Training Config ===
batch_size: 1 # the actual batch size also needs to multiply with |preference_pairs|
beta: 1.0
dropout: 0.1
gemma: 0.0
gradient_accumulation_steps: 1
label_smoothing: 0.0
loss_type: "scaled_simpo"
lr: 0.08
n_epochs: 1
reference_free: false
simpo_scaler: 1.0
train_on_negative: true
weight_decay: 0.00

# === Intervention Config ===
intervention_positions: "all"
intervention_positions_dropout: 0.0
intervention_type: "addition" # clamping
low_rank_dimension: 1

# === Steering Config ===
<<<<<<< HEAD
steering_factors: [0.0, 2.0] # use_cmd_to_define
=======
steering_factors: [2.0] # use_cmd_to_define
>>>>>>> 2a46a1c5 (Forward Still Bug)
steering_prompt_type: "blend_in"
substraction_type: "null_it_out" # normal or null_it_out





